import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en" className="bg-black">
    //   {/* <body className={poppins.className}> */}
    //   <body className="bg-red-500">
    //     <div className="bg-blue-600">
    //       <div className="bg-green-500">
    //         <NavBar />
    //       </div>
    //       {children}
    //       <div className="fixed left-0 bottom-0 w-full">
    //         {/* <div className=""> */}
    //         <Footer />
    //       </div>
    //     </div>
    //   </body>
    // </html>

    <html lang="en">
      <body className="m-0">
        <div>
          <NavBar />
          <>{children}</>
          <Footer />
        </div>
      </body>
    </html>
  );
}
